#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# TeX, /usr/local/bin, and current directory
export PATH=$HOME/bin:/usr/local/bin:/usr/local/texlive/2013/bin/x86_64-darwin:$PATH:/usr/games/bin/
export PATH=/usr/local/git/bin:$PATH:/opt/local/bin:/opt/local/sbin # Add git and other commands
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" # GNU coreutils
PATH=$PATH:. # Add current directory last

CDPATH=.:~ # Default to home if no directory found.

# export MANPATH="/usr/local/man:$MANPATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:/usr/games/man/:$MANPATH"

DISABLE_LS_COLORS="false"
alias l='/usr/local/bin/gls --color=auto --group-directories-first'
alias ls='/usr/local/bin/gls --color=auto --group-directories-first'
alias make='make -j2'
alias rot='/Users/jessefrohlich/codingProjects/macFlip/Resources/fb-rotate -d 0 -r'
#eval `gdircolors $HOME/.zsh_ls_colors/dircolors.ansi-universal`
#eval `gdircolors $HOME/.zsh_ls_colors/dircolors.ansi-light`
eval `gdircolors $HOME/.zsh_ls_colors/dircolors.ansi-dark`

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
